name: CICD (Staging, Prod)

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - README_DOCKER.md
      - CONTRIBUTING.md
  
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  
  test-build:
    uses: ./.github/workflows/template-test-build.yml
    secrets: inherit
    
  staging-deploy:
    needs: test-build
    uses: ./.github/workflows/template-deploy-environment.yml
    with:
      environment: Staging
    secrets: inherit
    
  prod-deploy:
    needs: staging-deploy
    uses: ./.github/workflows/template-deploy-environment.yml
    with:
      environment: Production
    secrets: inherit
