name: PR - Test build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
      - name: Test Svelte build
        run: |
          cd ui
          npm i
          npm run build
      - name: Test Firebase API build
        run: |
          cd api/functions
          npm i
          npm run lint
          npm run test
      - name: Deploy Hosting to Staging
        env:
          FIREBASETOKEN: ${{ secrets.FIREBASETOKEN }}
        run: |
          cd ui
          firebase use ssw-codeauditor-staging-f8357
          firebase projects:list
          npm i
          firebase deploy --token ${{ secrets.FIREBASETOKEN }} --only hosting
      - name: Deploy Function to Staging
        env:
          FIREBASETOKEN: ${{ secrets.FIREBASETOKEN }}
        run: |
          cd api/functions
          firebase use ssw-codeauditor-staging-f8357
          firebase projects:list
          npm i
          firebase deploy --token ${{ secrets.FIREBASETOKEN }} --only functions